name: Secrets Production

on:
  workflow_dispatch:
  workflow_call:

env:
  AWS_REGION_STAGING: us-east-1
  TF_VERSION: 1.11.1
  WORK_DIR_STAGING: environments/Staging/

jobs:
  Terraform-Apply-Staging:
    name: Terraform-Apply-Staging
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_STAGING }}

      - name: Apply
        working-directory: ${{ env.WORK_DIR_STAGING }}
        run: |
          terraform init
          terraform apply -auto-approve