name: Secrets Staging

on:
  workflow_dispatch:

jobs:
  Update-Secrets-Staging:
    name: Update-Secrets-Staging
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

#============================================
# Auth Service
#============================================
      - name: Update secret - auth-service/config
        env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
        run: |
          SECRET=$(jq -n \
            --arg master_key "$MASTER_KEY" \
            '{MASTER_KEY: $master_key}')
          aws secretsmanager put-secret-value \
            --secret-id togglemaster/staging/auth-service/config \
            --secret-string "$SECRET"

#============================================
# Flag Service
#============================================
      - name: Update secret - flag-service/config
        env:
          AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
        run: |
          SECRET=$(jq -n \
            --arg auth_service_url "$AUTH_SERVICE_URL" \
            '{AUTH_SERVICE_URL: $auth_service_url}')
          aws secretsmanager put-secret-value \
            --secret-id togglemaster/staging/flag-service/config \
            --secret-string "$SECRET"

#============================================
# Targeting Service
#============================================
      - name: Update secret - targeting-service/config
        env:
          AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
        run: |
          SECRET=$(jq -n \
            --arg auth_service_url "$AUTH_SERVICE_URL" \
            '{AUTH_SERVICE_URL: $auth_service_url}')
          aws secretsmanager put-secret-value \
            --secret-id togglemaster/staging/targeting-service/config \
            --secret-string "$SECRET"

#============================================
# Evaluation Service
#============================================
      - name: Update secret - evaluation-service/urls
        env:
          FLAG_SERVICE_URL: ${{ secrets.FLAG_SERVICE_URL }}
          TARGETING_SERVICE_URL: ${{ secrets.TARGETING_SERVICE_URL }}
        run: |
          SECRET=$(jq -n \
            --arg flag_service_url "$FLAG_SERVICE_URL" \
            --arg targeting_service_url "$TARGETING_SERVICE_URL" \
            '{FLAG_SERVICE_URL: $flag_service_url, TARGETING_SERVICE_URL: $targeting_service_url}')
          aws secretsmanager put-secret-value \
            --secret-id togglemaster/staging/evaluation-service/urls \
            --secret-string "$SECRET"

#============================================
# Analytics Service
#============================================
      - name: Update secret - analytics-service/credentials
        env:
          ANALYTICS_AWS_ACCESS_KEY_ID: ${{ secrets.ANALYTICS_AWS_ACCESS_KEY_ID }}
          ANALYTICS_AWS_SECRET_ACCESS_KEY: ${{ secrets.ANALYTICS_AWS_SECRET_ACCESS_KEY }}
        run: |
          SECRET=$(jq -n \
            --arg access_key "$ANALYTICS_AWS_ACCESS_KEY_ID" \
            --arg secret_key "$ANALYTICS_AWS_SECRET_ACCESS_KEY" \
            '{AWS_ACCESS_KEY_ID: $access_key, AWS_SECRET_ACCESS_KEY: $secret_key}')
          aws secretsmanager put-secret-value \
            --secret-id togglemaster/staging/analytics-service/credentials \
            --secret-string "$SECRET"
